### ISSUE TITLE
Unable to install via Conda

### ISSUE THREAD

**Issue by aseetharam** [churchill-lab/alntools#5]
Hello, 

I'm following the guidelines posted in the installation guidelines of the documentation, but I'm running into the problem of incompatible packages. Is there any workaround?

As per instructions, when I enter:
```
conda install -c kbchoi emase
```
I get:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:



Package pysam conflicts for:
emase -> pysam[version='>=0.6']
Package python conflicts for:
emase -> python=2.7
Package libffi conflicts for:
python=2.7.13 -> libffi=3.2
Package _libgcc_mutex conflicts for:
libgcc-ng=7.2.0 -> _libgcc_mutex=[build=main]
Package sqlite conflicts for:
python=2.7.13 -> sqlite[version='3.13.*|>=3.20.1,<4.0a0']
Package cython conflicts for:
emase -> cython[version='>=0.13']
Package libstdcxx-ng conflicts for:
python=2.7.13 -> libstdcxx-ng[version='>=7.2.0']
Package biopython conflicts for:
emase -> biopython[version='>=1.63']
Package zlib conflicts for:
python=2.7.13 -> zlib[version='1.2.*|>=1.2.11,<1.3.0a0']
Package ncurses conflicts for:
python=2.7.13 -> ncurses[version='5.9.*|6.0.*']
Package numpy conflicts for:
emase -> numpy==1.8.2
Package scipy conflicts for:
emase -> scipy==0.13.3
Package openssl conflicts for:
python=2.7.13 -> openssl=1.0
Package pip conflicts for:
python=2.7.13 -> pip
Package libgcc-ng conflicts for:
python=2.7.13 -> libgcc-ng[version='>=7.2.0']
zlib=1.2.11 -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
Package tk conflicts for:
python=2.7.13 -> tk[version='8.5.*|8.6.*']
Package pytables conflicts for:
emase -> pytables==3.1.0
Package numexpr conflicts for:
emase -> numexpr==2.3.1
Package readline conflicts for:
python=2.7.13 -> readline[version='6.2.*|7.*']
```

**Comment by kbchoi-jax** [comment]
Hi Arun,

Are you trying to run alntools or emase?

Thanks,

**Comment by aseetharam** [comment]
Thanks for the reply @kbchoi-jax! I'm actually trying to install `alntools` as per the instructions provided [here](https://churchill-lab.github.io/alntools/). Eventually, we would like to run the `emase` (`emase-zero`) as well. 

Thanks,

**Comment by kbchoi-jax** [comment]
I see. Since some change in conda, my one-liner installers are not working right now. Unfortunately I am committed to some other big projects. Would [a docker image](https://hub.docker.com/r/kbchoi/gbrs) help? You will have to first pull the image like this.

```
$ docker pull kbchoi/gbrs
```
And then run it like this.
```
$ docker run -i -t gbrs
```

It has both alntools and emase-zero. To use alntools you have to do the following.

```
(base) # conda activate alntools
```
`emase-zero` is available without any venv activation. Let me know how it goes. And feel free to [contact me](mailto:kb.choi@jax.org) if you need help on using my tools for your project.

**Comment by aseetharam** [comment]
That's wonderful! I wasn't aware of this, thanks for pointing this out. I'll pull this image and give it a try.

Thanks,
